ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY gitea-runner/modules/common.sh gitea-runner/modules/test.sh /tmp/
RUN bash /tmp/test.sh && rm -f /tmp/*.sh

ENV JAVA_HOME=/opt/jdk-25 \
    JMETER_HOME=/opt/jmeter \
    PATH="/opt/jdk-25/bin:/opt/jmeter/bin:${PATH}" \
    GITEA_RUNNER_LABELS_DEFAULT='ubuntu-latest,ubuntu-26.04,jmeter'
