ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY gitea-runner-ubuntu/modules/common.sh gitea-runner-ubuntu/modules/graalvm-jdk25.sh gitea-runner-ubuntu/modules/settings.xml /tmp/
RUN bash /tmp/graalvm-jdk25.sh && rm -f /tmp/*.sh /tmp/settings.xml

ENV JAVA_HOME=/opt/graalvm-jdk-25 \
    MAVEN_HOME=/opt/maven \
    PATH="/opt/graalvm-jdk-25/bin:/opt/maven/bin:${PATH}" \
    GITEA_RUNNER_LABELS_DEFAULT='ubuntu-latest,ubuntu-26.04,ubuntu-graalvm-jdk-25'
