ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY gitea-runner-ubuntu/modules/common.sh gitea-runner-ubuntu/modules/jdk25.sh gitea-runner-ubuntu/modules/settings.xml /tmp/
RUN bash /tmp/jdk25.sh && rm -f /tmp/*.sh /tmp/settings.xml

ENV JAVA_HOME=/opt/jdk-25 \
    MAVEN_HOME=/opt/maven \
    PATH="/opt/jdk-25/bin:/opt/maven/bin:${PATH}" \
    GITEA_RUNNER_LABELS_DEFAULT='ubuntu-latest,ubuntu-26.04,ubuntu-jdk-25'
