name: download_file

on:
  workflow_dispatch:
    inputs:
      download_file:
        description: '请填写下载地址'
        required: true
        default: ''

env:
  HUAWEICLOUD_IAM_AK: "${{ secrets.HUAWEICLOUD_IAM_AK }}"
  HUAWEICLOUD_IAM_SK: "${{ secrets.HUAWEICLOUD_IAM_SK }}"

jobs:
  build:
    name: download_file
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: DockerHub to SWR
        run: |
          docker login -u cn-south-1@$HUAWEICLOUD_IAM_AK -p $HUAWEICLOUD_IAM_SK swr.cn-south-1.myhuaweicloud.com
          set -ex
          
          images="${{ github.event.inputs.download_file }}"
          curl -o file ${images}
          
          current_datetime=$(date +'%Y%m%d_%H%M%S')
          docker build -t swr.cn-south-1.myhuaweicloud.com/gsc-hub/file:${current_datetime} -f Dockerfile_download_file .
          
          docker push swr.cn-south-1.myhuaweicloud.com/gsc-hub/file:${current_datetime}

      - name: Clean up intermediate files
        run: |
          rm file
