name: index-tts

on:
  workflow_dispatch:

env:
  HUAWEICLOUD_IAM_AK: "${{ secrets.HUAWEICLOUD_IAM_AK }}"
  HUAWEICLOUD_IAM_SK: "${{ secrets.HUAWEICLOUD_IAM_SK }}"

jobs:
  build:
    name: index-tts image
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: clean disk
        run: |
          pwd
          id
          uname -a
          docker info
          docker images
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/google /usr/lib/jvm /usr/lib/google-cloud-sdk /usr/lib/llvm* /usr/lib/firefox /opt/hostedtoolcache /usr/share/miniconda /usr/share/gradle-9.1.0
          sudo docker system prune --all --force --volumes
          sudo apt-get clean
          df -h
          docker images

      - name: monitor disk usage during build
        run: |
          sudo du -h / --max-depth=1 | sort -hr || true
          sudo find / -type f -size +100M -exec ls -alh {} \; | head -20
          sudo du -h /opt --max-depth=1 | sort -hr || true
          sudo du -h /usr --max-depth=1 | sort -hr || true
          sudo du -h /usr/lib --max-depth=1 | sort -hr || true
          sudo du -h /usr/share --max-depth=1 | sort -hr || true
          sudo du -h /usr/local --max-depth=1 | sort -hr || true
          df -h

      - name: git checkout
        uses: actions/checkout@v4

      - name: build container image
        run: |
          docker login -u cn-southwest-2@$HUAWEICLOUD_IAM_AK -p $HUAWEICLOUD_IAM_SK swr.cn-southwest-2.myhuaweicloud.com
          set -ex
          
          current_datetime="$(date +'%Y%m%d_%H%M%S')"
          artifact_image_url=swr.cn-southwest-2.myhuaweicloud.com/gsc-hub/index-tts:${current_datetime}-x86_64
          docker build -f index-tts-2/Dockerfile --squash --no-cache -t ${artifact_image_url} .
          
          docker images
          df -h
          pwd
          
          docker push ${artifact_image_url}
          docker save "${artifact_image_url}" | gzip > ${current_datetime}-x86_64.tar.gz

          ls -alh
          df -h

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: images.tar.gz
          path: "*-x86_64.tar.gz"
          retention-days: 1  # 将保留天数设置为1天 最多可设置90天

      - name: clean up intermediate files
        run: |
          rm -rf *.tar
          rm -rf *.tar.gz
