name: indextts

on:
  workflow_dispatch:

env:
  HUAWEICLOUD_IAM_AK: "${{ secrets.HUAWEICLOUD_IAM_AK }}"
  HUAWEICLOUD_IAM_SK: "${{ secrets.HUAWEICLOUD_IAM_SK }}"

jobs:
  main_job:
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Shanghai
    outputs:
      current_datetime: ${{ steps.global_env.outputs.current_datetime }}
      current_user: ${{ github.actor }}
    steps:
      - name: Generate multiple timestamp formats
        id: global_env
        run: |
          echo "current_datetime=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

  ubuntu_container_image_build:
    runs-on: ubuntu-24.04
    needs: main_job
    env:
      TZ: Asia/Shanghai
      current_datetime: ${{ needs.main_job.outputs.current_datetime }}
      current_user: ${{ needs.main_job.outputs.current_user }}
    steps:
      - name: clean disk
        run: |
          pwd
          id
          uname -a
          docker info
          docker images
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/google /usr/lib/jvm /usr/lib/google-cloud-sdk /usr/lib/llvm* /usr/lib/firefox /opt/hostedtoolcache /usr/share/miniconda /usr/share/gradle-9.1.0 /usr/local/.ghcup /usr/local/julia1.11.7 /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
          df -h
          docker images

      - name: monitor disk usage during build
        run: |
          sudo du -h /opt --max-depth=1 | sort -hr || true
          sudo du -h /usr --max-depth=1 | sort -hr || true
          sudo du -h /usr/lib --max-depth=1 | sort -hr || true
          sudo du -h /usr/share --max-depth=1 | sort -hr || true
          sudo du -h /usr/local --max-depth=1 | sort -hr || true
          sudo du -h /usr/local/share --max-depth=1 | sort -hr || true
          sudo du -h /usr/local/bin --max-depth=1 | sort -hr || true
          sudo du -h /usr/local/lib --max-depth=1 | sort -hr || true
          df -h

      - name: git checkout
        uses: actions/checkout@v4

      - name: build container image
        run: |
          docker login -u cn-southwest-2@$HUAWEICLOUD_IAM_AK -p $HUAWEICLOUD_IAM_SK swr.cn-southwest-2.myhuaweicloud.com
          set -ex
          
          artifact_image_url=swr.cn-southwest-2.myhuaweicloud.com/gsc-hub/indextts:${current_datetime}-ubuntu-x86_64
          docker build -f indextts/ubuntu/Dockerfile --squash --no-cache -t ${artifact_image_url} .
          
          docker images
          df -h
          pwd
          
          docker push ${artifact_image_url}

          ls -alh
          df -h

      - name: login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push to ghcr
        uses: docker/push-action@v2
        with:
          tags: |
            ${current_user}/indextts:latest
            ${current_user}/indextts:${current_datetime}-ubuntu-x86_64

  openeuler_container_image_build:
    runs-on: ubuntu-24.04
    needs: main_job
    env:
      TZ: Asia/Shanghai
      current_datetime: ${{ needs.main_job.outputs.current_datetime }}
      current_user: ${{ needs.main_job.outputs.current_user }}
    steps:
      - name: clean disk
        run: |
          pwd
          id
          uname -a
          docker info
          docker images
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/google /usr/lib/jvm /usr/lib/google-cloud-sdk /usr/lib/llvm* /usr/lib/firefox /opt/hostedtoolcache /usr/share/miniconda /usr/share/gradle-9.1.0 /usr/local/.ghcup /usr/local/julia1.11.7 /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
          df -h
          docker images

      - name: monitor disk usage during build
        run: |
          sudo du -h /opt --max-depth=1 | sort -hr || true
          sudo du -h /usr --max-depth=1 | sort -hr || true
          sudo du -h /usr/lib --max-depth=1 | sort -hr || true
          sudo du -h /usr/share --max-depth=1 | sort -hr || true
          sudo du -h /usr/local --max-depth=1 | sort -hr || true
          sudo du -h /usr/local/share --max-depth=1 | sort -hr || true
          sudo du -h /usr/local/bin --max-depth=1 | sort -hr || true
          sudo du -h /usr/local/lib --max-depth=1 | sort -hr || true
          df -h

      - name: git checkout
        uses: actions/checkout@v4

      - name: build container image
        run: |
          docker login -u cn-southwest-2@$HUAWEICLOUD_IAM_AK -p $HUAWEICLOUD_IAM_SK swr.cn-southwest-2.myhuaweicloud.com
          set -ex
          
          artifact_image_url=swr.cn-southwest-2.myhuaweicloud.com/gsc-hub/indextts:${current_datetime}-openeuler-x86_64
          docker build -f indextts/openeuler/Dockerfile --squash --no-cache -t ${artifact_image_url} .
          
          docker images
          df -h
          pwd
          
          docker push ${artifact_image_url}

          ls -alh
          df -h

      - name: login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push to ghcr
        uses: docker/push-action@v2
        with:
          tags: |
            ${current_user}/indextts:${current_datetime}-openeuler-x86_64